# Generated by Django 5.1.4 on 2025-02-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_borrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='Books.category'),
        ),
        migrations.AlterField(
            model_name='books',
            name='categories',
            field=models.ManyToManyField(related_name='book_categories', to='Books.category'),
        ),
    ]
